question_bank = {
    "non-inductive proof": {
        "Exercise Set #4.1": {
            ("#31", "direct proof"),
        },
        "Exercise Set #4.2": {
            ("#5", "direct proof"),
            ("#6", "direct proof"),
            ("#8", "direct proof"),
            ("#20", "direct proof"),
            ("#28", "direct proof"),
            ("#32", "direct proof"),
        },
        "Exercise Set #4.3": {
            ("#24", "direct proof"),
            ("#25", "direct proof"),
        },
        "Exercise Set #4.4": {
            ("#15", "direct proof"),
            ("#17", "direct proof"),
            ("#24", "direct proof"),
        },
        "Exercise Set #4.7": {
            ("#13", "contradiction proof"),
            ("#18", "contrapositive proof"),
            ("#24", "contrapositive proof"),
            ("#25", "contradiction proof"),
            ("#26", "contrapositive proof"),
            ("#28", "contrapositive proof"),
            ("#29", "contrapositive proof"),
        },
        "Exercise Set #4.7": {
            ("#6", "contradiction proof"),
            ("#7", "contradiction proof"),
            ("#18(a,b)", "contradiction proof"),
        },
        "Canvas (A3P1)": {
            ("#1", "direct proof"),
        },
    },
    "set theory": {
        "Exercise Set #6.1": {
            ("#5", ""),
            ("#6", ""),
            ("#7", ""),
            ("#26(a,b,c)", ""),
            ("#29", ""),
            ("#30", ""),
            ("#33(b,c)", ""),
            ("#34b", ""),
            ("#35d", ""),
        },
        "Exercise Set #6.2": {
            ("#6", ""),
            ("#9", ""),
            ("#10", ""),
            ("#11", ""),
            ("#13", ""),
            ("#14", ""),
            ("#16", ""),
            ("#17", ""),
            ("#20", ""),
        },
        "Exercise Set #6.3": {
            ("#36", ""),
            ("#37", ""),
            ("#38", ""),
            ("#39", ""),
            ("#40", ""),
            ("#41", ""),
            ("#42", ""),
        },
    },
    "inductive proof": {
        "Exercise Set #5.2": {
            ("#10", ""),
            ("#12", ""),
            ("#13", ""),
            ("#14", ""),
            ("#15", ""),
            ("#16", ""),
            ("#18", ""),
        },
        "Exercise Set #5.3": {
            ("#8", ""),
            ("#9", ""),
            ("#10", ""),
            ("#11", ""),
            ("#12", ""),
            ("#14", ""),
            ("#15", ""),
            ("#18", ""),
            ("#19", ""),
            ("#24", ""),
            ("#25", ""),
            ("#27", ""),
        },
    },
    "recursive definition": {
        "Exercise Set #5.7": {
            ("#5", ""),
            ("#6", ""),
            ("#7", ""),
        },
        "Exercise Set #5.9": {
            ("#16", ""),
            ("#17", ""),
            ("#18", ""),
            ("#19", ""),
        },
        "Canvas (A6)": {
            ("#1", ""),
            ("#2", ""),
            ("#3", ""),
            ("#4", ""),
            ("#5", ""),
        },
        "Final Review (Recursive Definition)": {
            ("#1", ""),
            ("#2", ""),
            ("#3", ""),
        },
    },
    "counting rules": {
        "Exercise Set #9.2": {
            ("#11c", ""),
            ("#16", ""),
            ("#17d", ""),
            ("#18c", ""),
            ("#28", ""),
        },
        "Exercise Set #9.3": {
            ("#5a", ""),
            ("#8c", ""),
            ("#29(f,g)", ""),
            ("#33(e,f)", ""),
            ("#34d", ""),
        },
        "Exercise Set #9.4": {
            ("#3", ""),
            ("#5", ""),
            ("#8", ""),
            ("#9", ""),
            ("#10", ""),
            ("#11", ""),
            ("#17", ""),
            ("#19", ""),
            ("#25", ""),
            ("#26", ""),
            ("#30", ""),
            ("#34", ""),
        },
        "Canvas (A7P1)": {
            ("#1", ""),
        },
    },
    "permutations and combinations": {
        "Exercise Set #9.2": {
            ("#32c", ""),
            ("#33", ""),
            ("#39(a,b,c,d)", ""),
        },
        "Exercise Set #9.5": {
            ("#6", ""),
            ("#8(b,c)", ""),
            ("#12", ""),
            ("#17", ""),
            ("#19", ""),
            ("#20(b,c)", ""),
        },
        "Exercise Set #9.6": {
            ("#3", ""),
            ("#4", ""),
            ("#10", ""),
            ("#11", ""),
            ("#14", ""),
            ("#19(a,b)", ""),
            ("#20(a,b)", ""),
        },
    },
    "graph theory": {
        "Exercise Set #4.9": {
            ("#13", ""),
            ("#16b", ""),
            ("#18", ""),
            ("#21(a,b,c)", ""),
            ("#23(e,f)", ""),
            ("#24(d,e)", ""),
        },
        "Exercise Set #10.1": {
            ("#2", ""),
            ("#9b", ""),
            ("#15", ""),
            ("#20", ""),
            ("#21", ""),
        },
        "Exercise Set #10.6": {
            ("#13", ""),
            ("#14", ""),
            ("#15", ""),
        },
        "Canvas (A9P1)": {
            ("#1", ""),
        },
        "Canvas (A10)": {
            ("#1", ""),
            ("#2", ""),
        },
    },
}
