question_bank = {
    "non-inductive proof": {
        "Exercise Set #4.1": {
            ("#31", "direct proof, even/odd"),
        },
        "Exercise Set #4.2": {
            ("#5", "direct proof, even/odd"),
            ("#6", "direct proof, even/odd"),
            ("#8", "direct proof, even/odd"),
            ("#20", "direct proof, even/odd"),
            ("#28", "direct proof, even/odd"),
            ("#32", "direct proof, square"),
        },
        "Exercise Set #4.3": {
            ("#24", "direct proof, rational/irrational"),
            ("#25", "direct proof, rational/irrational"),
        },
        "Exercise Set #4.4": {
            ("#15", "direct proof, division"),
            ("#17", "direct proof, division"),
            ("#24", "direct proof, division"),
        },
        "Exercise Set #4.7": {
            ("#13", "contradiction proof, rational/irrational"),
            ("#18", "contradiction proof, rational/irrational"),
            ("#24", "contradiction/contrapositive proof, rational/irrational"),
            ("#25", "contradiction/contrapositive proof, even/odd"),
            ("#26", "contradiction/contrapositive proof, division"),
            ("#28", "contradiction/contrapositive proof, division"),
            ("#29", "contradiction/contrapositive proof, even/odd"),
        },
        "Exercise Set #4.8": {
            ("#6", "contradiction/contrapositive proof, rational/irrational"),
            ("#7", "contradiction/contrapositive proof, rational/irrational"),
            ("#18(a,b)", "contradiction/contrapositive proof, even/odd, rational/irrational"),
        },
        "Canvas (A3P1)": {
            ("#1", "direct proof, rational/irrational"),
        },
    },
    "set theory": {
        "Exercise Set #6.1": {
            ("#5", "subset proof"),
            ("#6", "subset proof"),
            ("#7", "subset proof"),
            ("#26(a,b,c)", "partition"),
            ("#29", "partition"),
            ("#30", "partition"),
            ("#33(b,c)", "power set"),
            ("#34b", "set mathematics"),
            ("#35d", "set mathematics"),
        },
        "Exercise Set #6.2": {
            ("#6", "element argument proof"),
            ("#9", "element argument proof"),
            ("#10", "element argument proof"),
            ("#11", "element argument proof"),
            ("#13", "element argument proof"),
            ("#14", "element argument proof, single"),
            ("#16", "element argument proof, if-then"),
            ("#17", "element argument proof, if-then"),
            ("#20", "element argument proof, if-then"),
        },
        "Exercise Set #6.3": {
            ("#36", "algebraic proof"),
            ("#37", "algebraic proof"),
            ("#38", "algebraic proof"),
            ("#39", "algebraic proof"),
            ("#40", "algebraic proof"),
            ("#41", "set identity"),
            ("#42", "set identity"),
        },
    },
    "inductive proof": {
        "Exercise Set #5.2": {
            ("#10", "weak mathematical induction, sum"),
            ("#12", "weak mathematical induction, sum"),
            ("#13", "weak mathematical induction, sum"),
            ("#14", "weak mathematical induction, sum"),
            ("#15", "weak mathematical induction, sum"),
            ("#16", "weak mathematical induction, product"),
            ("#18", "weak mathematical induction, product"),
        },
        "Exercise Set #5.3": {
            ("#8", "weak mathematical induction, division"),
            ("#9", "weak mathematical induction, division"),
            ("#10", "weak mathematical induction, division"),
            ("#11", "weak mathematical induction, division"),
            ("#12", "weak mathematical induction, division"),
            ("#14", "weak mathematical induction, division"),
            ("#15", "weak mathematical induction, division"),
            ("#18", "weak mathematical induction, inequality"),
            ("#19", "weak mathematical induction, inequality"),
            ("#24", "weak mathematical induction, sequence"),
            ("#25", "weak mathematical induction, sequence"),
            ("#27", "weak mathematical induction, sequence"),
        },
    },
    "recursive definition": {
        "Exercise Set #5.7": {
            ("#5", "explicit formula"),
            ("#6", "explicit formula"),
            ("#7", "explicit formula"),
        },
        "Exercise Set #5.9": {
            ("#16", "recursive definition"),
            ("#17", "recursive definition"),
            ("#18", "recursive definition"),
            ("#19", "recursive definition"),
        },
        "Canvas (A6)": {
            ("#1, #2", "explicit formula, weak mathematical induction"),
            ("#3", "explicit formula"),
            ("#4", "recursive definition"),
            ("#5", "recursive definition"),
        },
        "Final Review (Recursive Definition)": {
            ("#1", "recursive definition"),
            ("#2", "recursive definition"),
            ("#3", "recursive definition"),
        },
    },
    "counting rules": {
        "Exercise Set #9.2": {
            ("#11c", "multiplication, bit string"),
            ("#16", "multiplication, digits"),
            ("#17d", "multiplication, digits"),
            ("#18c", "multiplication, digits"),
            ("#28", "multiplication, iteration"),
        },
        "Exercise Set #9.3": {
            ("#5a", "multiplication, digits"),
            ("#8c", "multiplication, at least one"),
            ("#33(e,f)", "inclusion/exclusion"),
            ("#34d", "inclusion/exclusion"),
        },
        "Exercise Set #9.4": {
            ("#3", "pigeonhole principle"),
            ("#5", "pigeonhole principle, remainder"),
            ("#8", "pigeonhole principle, subset"),
            ("#9", "pigeonhole principle"),
            ("#10", "pigeonhole principle"),
            ("#11", "pigeonhole principle"),
            ("#17", "pigeonhole principle, remainder"),
            ("#19", "pigeonhole principle"),
            ("#25", "pigeonhole principle"),
            ("#26", "pigeonhole principle"),
            ("#30", "pigeonhole principle"),
            ("#34", "pigeonhole principle, subset"),
        },
        "Canvas (A7P1)": {
            ("#1", "inclusion/exclusion"),
        },
    },
    "permutations and combinations": {
        "Exercise Set #9.2": {
            ("#32c", "permutation, letters"),
            ("#33", "permutation"),
            ("#39(a,b,c,d)", "permutation, letters"),
        },
        "Exercise Set #9.5": {
            ("#6", "combination"),
            ("#8(b,c)", "combination"),
            ("#12", "combination"),
            ("#17", "combination"),
            ("#19", "combination, distinguishable letters"),
            ("#20(b,c)", "combination, distinguishable letters"),
        },
        "Exercise Set #9.6": {
            ("#3, #19", "r-combination"),
            ("#4, #20", "r-combination"),
            ("#10", "r-combination, equation"),
            ("#11", "r-combination, equation"),
            ("#14", "r-combination, equation"),
        },
        "Canvas (A8P1)": {
            ("#1", "permutation, round table"),
            ("#2", "permutation, letters"),
            ("#3", "permutation, letters"),
        },
    },
    "graph theory": {
        "Exercise Set #4.9": {
            ("#13", "handshake theorem"),
            ("#16b", "handshake theorem"),
            ("#18", "handshake theorem"),
            ("#23(e,f)", "bipartite graph"),
            ("#24(d,e)", "bipartite graph"),
        },
        "Exercise Set #10.1": {
            ("#2", "graph definition"),
            ("#9b", "Euler circuit"),
            ("#15", "Euler circuit"),
            ("#20", "Euler trial"),
            ("#21", "Euler trial"),
        },
        "Exercise Set #10.6": {
            ("#13", "Dijkstra's algorithm"),
            ("#14", "Dijkstra's algorithm"),
            ("#15", "Dijkstra's algorithm"),
        },
        "Canvas (A9P1)": {
            ("#1", "graph definition"),
        },
        "Canvas (A10)": {
            ("#1", "Dijkstra's algorithm"),
            ("#2", "Dijkstra's algorithm"),
        },
    },
}
